name: Build

on: push

jobs:

  deb-package:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        target_arch: ["amd64", "armhf", "arm64"]
    steps:
      - name: GitHub Environment Variables Action
        uses: FranzDiebold/github-env-vars-action@v1.2.1

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Patch target distribution in Debian changelog
        # touchegg (x.y.z) DISTRO; urgency=medium
        # -z to replace only the first occurrence
        # ([)] ) - Group 0, find the first ") "
        # (\w+)  - Group 1, find a word (DISTRO)
        # \1$(lsb_release -c -s) - Replace group 1 with the target distribution name
        run: |
          sed -zr "s/([)] )(\w+)/\1bionic/" ${{ github.workspace }}/debian/changelog > ${{ github.workspace }}/debian/changelog
        # sed -zr "s/([)] )(\w+)/\1$(lsb_release -c -s)/" ${{ github.workspace }}/debian/changelog > ${{ github.workspace }}/debian/changelog

      - name: Get changelog
        id: changelog
        uses: juliangruber/read-file-action@v1
        with:
          path: ${{ github.workspace }}/debian/changelog
      - name: Echo changelog
        run: echo ${{ steps.changelog.outputs.content }}


        run: echo ::set-output name=changelog::$(cat ${{ github.workspace }}/debian/changelog)
      - name: Test output
        run: echo ${{ steps.vars.outputs.changelog }}

      - name: Build Debian package
        uses: pi-top/action-debian-package@v0.2.1
        with:
          source_directory: "${{ github.workspace }}"
          artifacts_directory: "${{ github.workspace }}/artifacts"

          docker_image: "ubuntu:18.04"
          distribution: "bionic"
          target_architecture: ${{ matrix.target_arch }}

          lintian_opts: "--dont-check-part nmu --no-tag-display-limit --display-info --show-overrides"
          # Package uses latest packaging syntax and Lintian opts/tags
          dpkg_buildpackage_opts: "--no-sign --no-check-builddeps --post-clean"

      - name: Upload Debian package artifacts
        uses: "actions/upload-artifact@v2"
        with:
          name: "${{ env.GITHUB_REPOSITORY_NAME }}-#${{ env.GITHUB_SHA_SHORT }}-${{matrix.target_arch}}-deb"
          path: "${{ github.workspace }}/artifacts"
